name: iOS Pull Request Workflow

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - '**'

jobs:
  build-and-test:
    name: Build and Test iOS App
    runs-on: macos-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cancel previous tasks
        uses: styfle/cancel-workflow-action@0.9.1
          with:
            access_token: ${{ github.token }}

      - name: Xcode Select
         uses: maxim-lobanov/setup-xcode@v1
          with:
             xcode-version: latest-stable
      
      - uses: ruby/setup-ruby@v1

      - name: Install Bundler
        run: gem install bundler
      
      - name: Install gems
        run: bundle install
      
      - name: Run tests
        run: bundle exec fastlane unit_test


      # Set up CocoaPods if your project uses it
      # - name: Install CocoaPods
      #   run: |
      #     sudo gem install cocoapods
      #     pod install
      #   working-directory: ./YourProjectDirectory # Adjust this if needed

